### PR TITLE
Data2viz logo

### PR DESCRIPTION
**Pull request by gzoritchak**
The current logo miss the information of data2viz. What logo should we use?

### CODE REVIEW

**Comment by gzoritchak** [comment]
First proposition of @azertypow : 
image

**Comment by gzoritchak** [comment]
We should try also with .io + lowercase.

**Comment by pmariac** [comment]
maybe 

▷Data2viz.Play ?

**Comment by azertypow** [comment]
# Caps variation:
image
image
image

# With ".io":
Makes sense of the domain name.
image
image
image

# Green color variation

image

Test with a green aligned to the green of the play button.
image

**Comment by gzoritchak** [comment]
> maybe
> 
> ▷Data2viz.Play ?

It can be the best option.

**Comment by azertypow** [comment]
@pmariac, test with data2viz.play
image

preference for versions 6 and 3.

@gzoritchak, I tested the version with **data2viz** in another color.
I think it's too much color.

**Comment by gzoritchak** [comment]
Go for v3.

**Pull request merged**
